apiVersion: v1
kind: ServiceAccount
metadata:
  name: srechallenge
  namespace: srechallenge

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: srechallenge-read
  namespace: srechallenge
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","watch","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: srechallenge-read-bind
subjects:
- kind: ServiceAccount
  name: srechallenge
  namespace: srechallenge
roleRef:
  kind: ClusterRole
  name: srechallenge-read
  apiGroup: rbac.authorization.k8s.io