{
 "title": "Lambda",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region" },
   {
    "name": "functionname",
    "label": "FunctionName",
    "query": {}
   },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   {
    "name": "apigatewayname",
    "label": "ApiGatewayName",
    "query": {}
   },
   {
    "name": "getloggroup",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Lambda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Simultaneous Executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "{{metric}}",
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Durations Average",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "FunctionName": "$functionname" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| limit 20\n| filter @type = \"REPORT\"\n| stats max(@memorySize / 1024 / 1024) as ReservedMemoryMB,\n    avg(@maxMemoryUsed / 1024 / 1024) as AverageMemoryUsedMB\n    ",
     "logGroupNames": [ "/aws/lambda/$functionname" ],
     "queryMode": "Logs",
     "region": "$region"
    }
   ]
  },
  {
   "title": "Invocations / Error",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "FunctionName": "$functionname" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "FunctionName": "$functionname" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Error logs Lambda",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, extra.error.status\n| sort @timestamp desc\n| limit 50\n| filter extra.error.status>=400 and extra.error.status<=499 and level='error'",
     "logGroupNames": [ "/aws/lambda/$functionname" ],
     "namespace": "AWS/ApiGateway",
     "queryMode": "Logs",
     "region": "$region"
    },
    {
     "expression": "fields @timestamp, @message, extra.error.status\n| sort @timestamp desc\n| limit 50\n| filter extra.error.status>=500 and extra.error.status<=599 and level='error'",
     "logGroupNames": [ "/aws/lambda/$functionname" ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  { "title": "Api Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HTTP Requests / Transactions Per Second API Gateway",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "ApiName": "$apigatewayname" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "ApiName": "$apigatewayname" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Api Gateway Error Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, status, ip, httpMethod\n| sort @timestamp desc\n| limit 50\n| filter status>=400 and status<=499",
     "logGroupNames": [ "$getloggroup" ],
     "queryMode": "Logs",
     "region": "$region"
    },
    {
     "expression": "fields @timestamp, @message, status, ip, httpMethod\n| sort @timestamp desc\n| limit 50\n| filter status>=500 and status<=599",
     "logGroupNames": [ "$getloggroup" ],
     "queryMode": "Logs",
     "region": "$region"
    }
   ]
  },
  {
   "title": "Latency ApiGateway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "ApiName": "$apigatewayname" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboard Guide",
     "type": "text",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "## Lambda & API Gateway Dashboard\n\nThe Grafana Dashboard for Lambda and AWS API Gateway is a monitoring tool that allows you to visualize data and performance metrics of services in a Lambda environment integrated with the AWS API Gateway. With this dashboard, it is possible to monitor in real-time the performance and availability of applications deployed in Lambda Function, as well as analyze the incoming and outgoing traffic in the AWS API Gateway. Additionally, the tool allows for the configuration of custom alerts based on performance thresholds defined by the user.\n\n## Getting Started\n\nFor the dashboard to work properly, API Gateway and lambda logs need to be enabled.\n\n### API Gateway\n\n1. Access the DevOps Portal platform.\n2. In the left-hand side menu, click on Infrastructure > Resource Management.\n3. Fill in the brand and environment fields that you want to change.\n4. Type the name of the Lambda that you want to add logs to in the search field.\n5. Click on the Lambda when it appears, and the edit form will appear.\n6. In the Logging and Metrics Control section, you can enable logging and configure the retention period.\n7. Turn on the Enable logging option.\n8. Turn on the Enable access logs option.\n9. Configure the desired retention period for logs.\n10. Configure the error level you want.\n\n### Lambda\n1.  Access the DevOps Portal platform.[Portal DevOps](https://amazonia.naturaeco.com/)\n2. In the left-hand side menu, click on Infrastructure > Resource Management.\n3. Fill in the brand and environment fields that you want to change.\n4. Type the name of the Lambda that you want to add logs to in the search field.\n5. Click on the Lambda when it appears, and the edit form will appear.\n6. In the Logging and Metrics Control section, you can enable logging and configure the retention period.\n\n## Data Sources\n\nData Source is a feature of Grafana that allows connecting to various data sources to collect information and visualize it on dashboards. These data sources can be databases, cloud services, APIs, among others. Grafana supports several types of data sources, such as MySQL, PostgreSQL, Elasticsearch, AWS CloudWatch, Prometheus, InfluxDB, Microsoft SQL Server, among others. By using data sources in Grafana, it is possible to create customized dashboards and view data from various sources in one place, making the analysis and monitoring of systems and services easier.\n\n#### Natura\n\n```scss\n@Production:\nCloudWatch-Producao | CloudWatch-Producao-SA\n\n@Homolog:\nCloudWatch-Hml\n\n@Quality:\nCloudWatch-Hml\n```\n\n#### Avon\n\n```scss\n@Production:\nCloudWatch-avon-mx-lego-gpp-prd\n\n@Homolog:\nCloudWatch-avon-mx-lego-gpp-hml\n```"
     }
    }
   ]
  }
 ]
}