variable "aws_region" {}
variable "cluster_name" {}
variable "k8s_version" {}
variable "cluster_vpc" {}
variable "cluster_vpc_id" {}
variable "eks_cluster_role_arn" {}
variable "aws_security_group" {}
variable "private_subnets_a" {}
variable "private_subnets_b" {}