{
 "title": "Deployments",
 "tags": [
  "kubernetes",
  "aws"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(node)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster=~\"^$cluster$\"},namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{cluster=~\"^$cluster$\",namespace=~\"^$namespace$\"},deployment)"
    }
   },
   {
    "name": "aggegracao",
    "label": "Aggregation",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_labels,cluster)"
    }
   },
   { "name": "datasource", "label": "Data Source Kubernetes", "query": "prometheus" },
   {
    "name": "apigatewayname",
    "label": "ApiGatewayName",
    "query": {}
   },
   { "name": "cloudwatchapigw", "label": "Datasource Api Gateway", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "getloggroup",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage / Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "200\n* sum(rate(container_cpu_usage_seconds_total{cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\"}[$aggegracao]))\n/ sum(kube_pod_container_resource_requests{resource=~\"cpu\",cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\"})"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "200 * sum(container_memory_working_set_bytes{cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\"}) / sum(kube_pod_container_resource_requests{resource=~\"memory\",cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\"})"
    }
   ]
  },
  {
   "title": "Usage(miliCPU)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\"}[$aggegracao])) * 1000"
    }
   ]
  },
  {
   "title": "Requests(miliCPU)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=~\"cpu\",cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\",job=\"kube-state-metrics\"}) * 1000\n"
    }
   ]
  },
  {
   "title": "Limits(miliCPU)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"^$deployment-[^-]*-[^-]*$\",namespace=~\"^$namespace$\"}) * 1000"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=~\"memory\",cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\",job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=~\"memory\",cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\",job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (MiliCPU)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|istio-proxy|\"}[$aggegracao])) by (pod) * 1000"
    }
   ]
  },
  {
   "title": "Memory Usage (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"^$cluster$\", namespace=~\"^$namespace$\", pod=~\"^$deployment-[a-z0-9]+-[a-z0-9]+\", container!~\"POD|istio-proxy|\"}) by(pod)"
    }
   ]
  },
  {
   "title": "Maximum Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=~\"^$deployment$\",namespace=~\"^$namespace$\"}"
    }
   ]
  },
  {
   "title": "Pods Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{cluster=~\"^$cluster$\",namespace=~\"^$namespace$\",deployment=~\"^$deployment\",container!~\"kube-state-metrics\"}"
    }
   ]
  },
  {
   "title": "Minimum replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=~\"^$deployment$\",namespace=~\"^$namespace$\"}"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "HTTP Requests / Transactions Per Second API Gateway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "ApiName": "$apigatewayname" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "period": "$aggegracao",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "ApiName": "$apigatewayname" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "period": "$aggegracao",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Api Gateway Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, status, ip, httpMethod\n| sort @timestamp desc\n| limit 50\n| filter status>=400 and status<=499",
     "logGroupNames": [ "$getloggroup" ],
     "namespace": "AWS/ApiGateway",
     "queryMode": "Logs",
     "region": "$region"
    },
    {
     "expression": "fields @timestamp, @message, status, ip, httpMethod\n| sort @timestamp desc\n| limit 50\n| filter status>=500 and status<=599",
     "logGroupNames": [ "$getloggroup" ],
     "namespace": "AWS/ApiGateway",
     "queryMode": "Logs",
     "region": "$region"
    }
   ]
  },
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboard Guide",
     "type": "text",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 34 },
     "options": {
      "content": "## Kubernetes & API Gateway Dashboard\n\nThe Grafana Dashboard for Kubernetes and AWS API Gateway is a monitoring tool that allows you to visualize data and performance metrics of services in a Kubernetes environment integrated with the AWS API Gateway. With this dashboard, it is possible to monitor in real-time the performance and availability of applications deployed in Kubernetes clusters, as well as analyze the incoming and outgoing traffic in the AWS API Gateway. Additionally, the tool allows for the configuration of custom alerts based on performance thresholds defined by the user.\n\n## Getting Started\n\nFor the dashboard to work properly, API Gateway logs need to be enabled.\n\n1. Access the DevOps Portal platform.\n2. In the left-hand side menu, click on Infrastructure > Resource Management.\n3. Fill in the brand and environment fields that you want to change.\n4. Type the name of the API Gateway that you want to add logs to in the search field.\n5. Click on the API Gateway when it appears, and the edit form will appear.\n6. In the Logging and Metrics Control section, you can enable logging and configure the retention period.\n7. Turn on the Enable logging option.\n8. Turn on the Enable access logs option.\n9. Configure the desired retention period for logs.\n10. Configure the error level you want.\n\n## Data Sources\n\nData Source is a feature of Grafana that allows connecting to various data sources to collect information and visualize it on dashboards. These data sources can be databases, cloud services, APIs, among others. Grafana supports several types of data sources, such as MySQL, PostgreSQL, Elasticsearch, AWS CloudWatch, Prometheus, InfluxDB, Microsoft SQL Server, among others. By using data sources in Grafana, it is possible to create customized dashboards and view data from various sources in one place, making the analysis and monitoring of systems and services easier.\n\n### Kubernetes\n\n#### Natura\n\n```bash\n# Production:\neks-prd-sa-east-1-share \n\n# Homolog:\neks-hml-sa-east-1-share\n\n# Quality:\neks-hml-sa-east-1-share \n```\n\n#### Avon\n\n```scss\n#Commercial\n\n@Production\neks-avon-mx-lego-gpp-prd-us-east-1-commercial\n\n@Homolog\neks-avon-mx-lego-gpp-hml-us-east-1-commercial\n```\n\n```scss\n#Cadastro-Unificado\n\n@Production\neks-avon-mx-lego-gpp-prd-us-east-1-cadastro-unificado\n\n@Homolog\neks-avon-mx-lego-gpp-hml-us-east-1-cadastro-unificado\n```\n\n```scss\n#Cadastro-Experiencia\n\n@Production\neks-avon-mx-lego-gxp-prd-us-east-1-gxp\n\n@Homolog\neks-avon-mx-lego-gxp-hml-us-east-1-gxp\n```\n\n### API Gateway\n\n#### Natura\n\n```scss\n@Production:\nCloudWatch-Producao | CloudWatch-Producao-SA\n\n@Homolog:\nCloudWatch-Hml\n\n@Quality:\nCloudWatch-Hml\n```\n\n#### Avon\n\n```scss\n@Production:\nCloudWatch-avon-mx-lego-gpp-prd\n\n@Homolog:\nCloudWatch-avon-mx-lego-gpp-hml\n```"
     }
    }
   ]
  }
 ]
}