---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: monitoring
  labels:
    app: grafana
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - name: k8s-cluster-monitoring
      folder: homelab
      options:
        path: /var/lib/grafana/dashboards
      orgId: 1
      type: file