name: Challenge-SonarCloud
on:
  pull_request:
    branches: [ main ]

  push:
    branches: 
      - 'feat/*'
      - 'ci/*'

jobs:
  run-ci:
    runs-on: ubuntu-20.04
    name: run-ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.5"
          cache: "pip"

      - name: Install Dependencies
        run: make install-dependencies 

      - name: Execute Lint
        run: make lint

      - name: Run unit test
        run: make unit-test-report-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "break_change:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Bump version and push tag
      #   id: tagging
      #   uses: mathieudutour/github-tag-action@v4.5
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag_prefix: v
      #     commit_sha: false

      - name: Build and push Docker image 
        uses: docker/build-push-action@v2 
        with: 
          context: .
          push: true
          tags: msnhd2/flask_docker:latest,msnhd2/flask_docker:${{ steps.versioning.outputs.version }}
  