name: Challenge-SonarCloud
on:
  pull_request:
    branches: [ main ]
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'
  push:
    branches: 
      - 'feat/*'
      - 'ci/*'

jobs:
  run-ci:
    runs-on: ubuntu-20.04
    name: run-ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.5"
          cache: "pip"

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: msnhd2/flask_docker
          tag-sha: true

      - name: Install Dependencies
        run: make install-dependencies 

      - name: Execute Lint
        run: make lint

      - name: Run unit test
        run: make unit-test-report-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bump version and push tag
        id: tagging
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Docker metadata
      #   id: metadata
      #   uses: crazy-max/ghaction-docker-meta@v1
      #   with:
      #     images: msnhd2/flask_docker
      #     tags: |
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Build and push Docker image 
        uses: docker/build-push-action@v2 
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.tagging.outputs.new_version }}
  